# Enable/disable/inspect auto-start of the herald tray icon on Windows.
# Installs a hidden VBScript launcher in the user's Startup folder (runs at
# logon) and, on enable, starts the tray immediately.
#   powershell -ExecutionPolicy Bypass -File setup-tray.ps1 enable
#   powershell -ExecutionPolicy Bypass -File setup-tray.ps1 disable
#   powershell -ExecutionPolicy Bypass -File setup-tray.ps1 status
#
# Why a .vbs and not a Start-Process / .lnk to powershell: a WSL- or
# script-launched powershell started detached does not attach to the interactive
# desktop, so its tray icon paints to an invisible window station. A VBScript run
# via wscript spawns the powershell as a child that inherits the interactive
# desktop, so the icon actually appears - both at logon and when launched now.

param([ValidateSet('enable', 'disable', 'status')][string]$Action = 'status')

$trayScript = Join-Path $PSScriptRoot "herald-tray.ps1"
$startup    = [Environment]::GetFolderPath('Startup')
$vbs        = Join-Path $startup "herald-tray.vbs"
$lnk        = Join-Path $startup "herald-tray.lnk"   # legacy launcher, superseded by the vbs
$wscript    = Join-Path $env:WINDIR "System32\wscript.exe"
$legacy     = @((Join-Path $startup "a2a-tray.vbs"), (Join-Path $startup "a2a-tray.lnk"))  # pre-rename launchers

function Stop-LegacyTray {
    Get-CimInstance Win32_Process -Filter "Name='powershell.exe'" |
        Where-Object { $_.CommandLine -like '*a2a-tray.ps1*' } |
        ForEach-Object { try { Stop-Process -Id $_.ProcessId -Force } catch {} }
}

function Stop-Tray {
    # Waits for the icons to actually go: Stop-Process returns before the process
    # has exited, and launching over a survivor leaves two icons and two menus.
    Get-CimInstance Win32_Process -Filter "Name='powershell.exe'" |
        Where-Object { $_.CommandLine -like '*herald-tray.ps1*' } |
        ForEach-Object { try { Stop-Process -Id $_.ProcessId -Force } catch {} }
    for ($i = 0; $i -lt 25 -and (Count-Tray) -gt 0; $i++) { Start-Sleep -Milliseconds 200 }
    return (Count-Tray)
}

function Count-Tray {
    (Get-CimInstance Win32_Process -Filter "Name='powershell.exe'" |
        Where-Object { $_.CommandLine -like '*herald-tray.ps1*' } | Measure-Object).Count
}

switch ($Action) {
    'enable' {
        $launcher = @"
' Auto-generated by setup-tray.ps1 - launches the herald tray hidden.
Set s = CreateObject("WScript.Shell")
s.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -File ""$trayScript""", 0, False
"@
        Set-Content -Path $vbs -Value $launcher -Encoding ASCII
        if (Test-Path $lnk) { Remove-Item $lnk -Force }   # drop the old shortcut
        foreach ($f in $legacy) { if (Test-Path $f) { Remove-Item $f -Force } }  # drop pre-rename launchers
        Stop-LegacyTray                                    # kill any pre-rename tray still running
        $left = Stop-Tray                                  # avoid stacking duplicates
        if ($left -gt 0) {
            Write-Host "Refusing to launch: $left tray process(es) would not stop. Close the icon from its Exit menu, then run enable again."
            break
        }
        & $wscript $vbs                                    # start it now (inherits the desktop)
        for ($i = 0; $i -lt 25 -and (Count-Tray) -lt 1; $i++) { Start-Sleep -Milliseconds 200 }
        Write-Host "Tray auto-start ENABLED ($vbs). Starts at login; launched now; running instances: $(Count-Tray)."
    }
    'disable' {
        Stop-Tray
        $removed = @()
        foreach ($f in @($vbs, $lnk)) { if (Test-Path $f) { Remove-Item $f -Force; $removed += $f } }
        if ($removed) { Write-Host "Tray auto-start disabled (removed $($removed -join ', '))" }
        else { Write-Host "Tray auto-start was not enabled." }
    }
    'status' {
        $running = Count-Tray
        if (Test-Path $vbs)      { Write-Host "Tray auto-start: ENABLED ($vbs); running instances: $running" }
        elseif (Test-Path $lnk)  { Write-Host "Tray auto-start: ENABLED via legacy shortcut ($lnk); running instances: $running" }
        else                     { Write-Host "Tray auto-start: disabled; running instances: $running" }
    }
}
